-- Migration 084 — Backfill users.country from full names to ISO 3166-1 alpha-2 codes
-- Covers every country in the COUNTRIES list in src/lib/timezone.ts.
-- Rows already holding a 2-character code (mock users from migration 083) are
-- skipped by the WHERE length(country) > 2 guard.

UPDATE public.users
SET country = CASE country
  WHEN 'Afghanistan'             THEN 'AF'
  WHEN 'Albania'                 THEN 'AL'
  WHEN 'Algeria'                 THEN 'DZ'
  WHEN 'Angola'                  THEN 'AO'
  WHEN 'Argentina'               THEN 'AR'
  WHEN 'Armenia'                 THEN 'AM'
  WHEN 'Australia'               THEN 'AU'
  WHEN 'Austria'                 THEN 'AT'
  WHEN 'Azerbaijan'              THEN 'AZ'
  WHEN 'Bahrain'                 THEN 'BH'
  WHEN 'Bangladesh'              THEN 'BD'
  WHEN 'Belarus'                 THEN 'BY'
  WHEN 'Belgium'                 THEN 'BE'
  WHEN 'Bolivia'                 THEN 'BO'
  WHEN 'Bosnia and Herzegovina'  THEN 'BA'
  WHEN 'Brazil'                  THEN 'BR'
  WHEN 'Bulgaria'                THEN 'BG'
  WHEN 'Cambodia'                THEN 'KH'
  WHEN 'Cameroon'                THEN 'CM'
  WHEN 'Canada'                  THEN 'CA'
  WHEN 'Chile'                   THEN 'CL'
  WHEN 'China'                   THEN 'CN'
  WHEN 'Colombia'                THEN 'CO'
  WHEN 'Croatia'                 THEN 'HR'
  WHEN 'Cuba'                    THEN 'CU'
  WHEN 'Czech Republic'          THEN 'CZ'
  WHEN 'Denmark'                 THEN 'DK'
  WHEN 'DR Congo'                THEN 'CD'
  WHEN 'Ecuador'                 THEN 'EC'
  WHEN 'Egypt'                   THEN 'EG'
  WHEN 'El Salvador'             THEN 'SV'
  WHEN 'Ethiopia'                THEN 'ET'
  WHEN 'Finland'                 THEN 'FI'
  WHEN 'France'                  THEN 'FR'
  WHEN 'Georgia'                 THEN 'GE'
  WHEN 'Germany'                 THEN 'DE'
  WHEN 'Ghana'                   THEN 'GH'
  WHEN 'Greece'                  THEN 'GR'
  WHEN 'Guatemala'               THEN 'GT'
  WHEN 'Haiti'                   THEN 'HT'
  WHEN 'Honduras'                THEN 'HN'
  WHEN 'Hungary'                 THEN 'HU'
  WHEN 'India'                   THEN 'IN'
  WHEN 'Indonesia'               THEN 'ID'
  WHEN 'Iran'                    THEN 'IR'
  WHEN 'Iraq'                    THEN 'IQ'
  WHEN 'Ireland'                 THEN 'IE'
  WHEN 'Israel'                  THEN 'IL'
  WHEN 'Italy'                   THEN 'IT'
  WHEN 'Ivory Coast'             THEN 'CI'
  WHEN 'Jamaica'                 THEN 'JM'
  WHEN 'Japan'                   THEN 'JP'
  WHEN 'Jordan'                  THEN 'JO'
  WHEN 'Kazakhstan'              THEN 'KZ'
  WHEN 'Kenya'                   THEN 'KE'
  WHEN 'Kuwait'                  THEN 'KW'
  WHEN 'Lebanon'                 THEN 'LB'
  WHEN 'Libya'                   THEN 'LY'
  WHEN 'Malaysia'                THEN 'MY'
  WHEN 'Mauritius'               THEN 'MU'
  WHEN 'Mexico'                  THEN 'MX'
  WHEN 'Moldova'                 THEN 'MD'
  WHEN 'Mongolia'                THEN 'MN'
  WHEN 'Morocco'                 THEN 'MA'
  WHEN 'Mozambique'              THEN 'MZ'
  WHEN 'Myanmar'                 THEN 'MM'
  WHEN 'Nepal'                   THEN 'NP'
  WHEN 'Netherlands'             THEN 'NL'
  WHEN 'New Zealand'             THEN 'NZ'
  WHEN 'Nigeria'                 THEN 'NG'
  WHEN 'North Korea'             THEN 'KP'
  WHEN 'Norway'                  THEN 'NO'
  WHEN 'Oman'                    THEN 'OM'
  WHEN 'Pakistan'                THEN 'PK'
  WHEN 'Panama'                  THEN 'PA'
  WHEN 'Paraguay'                THEN 'PY'
  WHEN 'Peru'                    THEN 'PE'
  WHEN 'Philippines'             THEN 'PH'
  WHEN 'Poland'                  THEN 'PL'
  WHEN 'Portugal'                THEN 'PT'
  WHEN 'Qatar'                   THEN 'QA'
  WHEN 'Romania'                 THEN 'RO'
  WHEN 'Russia'                  THEN 'RU'
  WHEN 'Rwanda'                  THEN 'RW'
  WHEN 'Saudi Arabia'            THEN 'SA'
  WHEN 'Senegal'                 THEN 'SN'
  WHEN 'Serbia'                  THEN 'RS'
  WHEN 'Singapore'               THEN 'SG'
  WHEN 'Slovakia'                THEN 'SK'
  WHEN 'Slovenia'                THEN 'SI'
  WHEN 'Somalia'                 THEN 'SO'
  WHEN 'South Africa'            THEN 'ZA'
  WHEN 'South Korea'             THEN 'KR'
  WHEN 'South Sudan'             THEN 'SS'
  WHEN 'Spain'                   THEN 'ES'
  WHEN 'Sri Lanka'               THEN 'LK'
  WHEN 'Sudan'                   THEN 'SD'
  WHEN 'Sweden'                  THEN 'SE'
  WHEN 'Switzerland'             THEN 'CH'
  WHEN 'Syria'                   THEN 'SY'
  WHEN 'Taiwan'                  THEN 'TW'
  WHEN 'Tanzania'                THEN 'TZ'
  WHEN 'Thailand'                THEN 'TH'
  WHEN 'Tunisia'                 THEN 'TN'
  WHEN 'Turkey'                  THEN 'TR'
  WHEN 'Uganda'                  THEN 'UG'
  WHEN 'Ukraine'                 THEN 'UA'
  WHEN 'United Arab Emirates'    THEN 'AE'
  WHEN 'United Kingdom'          THEN 'GB'
  WHEN 'United States'           THEN 'US'
  WHEN 'Uruguay'                 THEN 'UY'
  WHEN 'Uzbekistan'              THEN 'UZ'
  WHEN 'Venezuela'               THEN 'VE'
  WHEN 'Vietnam'                 THEN 'VN'
  WHEN 'Yemen'                   THEN 'YE'
  WHEN 'Zimbabwe'                     THEN 'ZW'
  WHEN 'Andorra'                      THEN 'AD'
  WHEN 'Antigua and Barbuda'          THEN 'AG'
  WHEN 'Bahamas'                      THEN 'BS'
  WHEN 'Barbados'                     THEN 'BB'
  WHEN 'Belize'                       THEN 'BZ'
  WHEN 'Benin'                        THEN 'BJ'
  WHEN 'Bhutan'                       THEN 'BT'
  WHEN 'Botswana'                     THEN 'BW'
  WHEN 'Brunei'                       THEN 'BN'
  WHEN 'Burkina Faso'                 THEN 'BF'
  WHEN 'Burundi'                      THEN 'BI'
  WHEN 'Cape Verde'                   THEN 'CV'
  WHEN 'Central African Republic'     THEN 'CF'
  WHEN 'Chad'                         THEN 'TD'
  WHEN 'Comoros'                      THEN 'KM'
  WHEN 'Republic of Congo'            THEN 'CG'
  WHEN 'Costa Rica'                   THEN 'CR'
  WHEN 'Cyprus'                       THEN 'CY'
  WHEN 'Djibouti'                     THEN 'DJ'
  WHEN 'Dominica'                     THEN 'DM'
  WHEN 'Dominican Republic'           THEN 'DO'
  WHEN 'Equatorial Guinea'            THEN 'GQ'
  WHEN 'Eritrea'                      THEN 'ER'
  WHEN 'Estonia'                      THEN 'EE'
  WHEN 'Eswatini'                     THEN 'SZ'
  WHEN 'Fiji'                         THEN 'FJ'
  WHEN 'Gabon'                        THEN 'GA'
  WHEN 'Gambia'                       THEN 'GM'
  WHEN 'Grenada'                      THEN 'GD'
  WHEN 'Guinea'                       THEN 'GN'
  WHEN 'Guinea-Bissau'                THEN 'GW'
  WHEN 'Guyana'                       THEN 'GY'
  WHEN 'Iceland'                      THEN 'IS'
  WHEN 'Kiribati'                     THEN 'KI'
  WHEN 'Kyrgyzstan'                   THEN 'KG'
  WHEN 'Laos'                         THEN 'LA'
  WHEN 'Latvia'                       THEN 'LV'
  WHEN 'Lesotho'                      THEN 'LS'
  WHEN 'Liberia'                      THEN 'LR'
  WHEN 'Liechtenstein'                THEN 'LI'
  WHEN 'Lithuania'                    THEN 'LT'
  WHEN 'Luxembourg'                   THEN 'LU'
  WHEN 'Madagascar'                   THEN 'MG'
  WHEN 'Malawi'                       THEN 'MW'
  WHEN 'Maldives'                     THEN 'MV'
  WHEN 'Mali'                         THEN 'ML'
  WHEN 'Malta'                        THEN 'MT'
  WHEN 'Marshall Islands'             THEN 'MH'
  WHEN 'Mauritania'                   THEN 'MR'
  WHEN 'Micronesia'                   THEN 'FM'
  WHEN 'Monaco'                       THEN 'MC'
  WHEN 'Montenegro'                   THEN 'ME'
  WHEN 'Namibia'                      THEN 'NA'
  WHEN 'Nauru'                        THEN 'NR'
  WHEN 'Nicaragua'                    THEN 'NI'
  WHEN 'Niger'                        THEN 'NE'
  WHEN 'North Macedonia'              THEN 'MK'
  WHEN 'Palau'                        THEN 'PW'
  WHEN 'Palestine'                    THEN 'PS'
  WHEN 'Papua New Guinea'             THEN 'PG'
  WHEN 'Saint Kitts and Nevis'        THEN 'KN'
  WHEN 'Saint Lucia'                  THEN 'LC'
  WHEN 'Saint Vincent and the Grenadines' THEN 'VC'
  WHEN 'Samoa'                        THEN 'WS'
  WHEN 'San Marino'                   THEN 'SM'
  WHEN 'São Tomé and Príncipe'        THEN 'ST'
  WHEN 'Seychelles'                   THEN 'SC'
  WHEN 'Sierra Leone'                 THEN 'SL'
  WHEN 'Solomon Islands'              THEN 'SB'
  WHEN 'Suriname'                     THEN 'SR'
  WHEN 'Tajikistan'                   THEN 'TJ'
  WHEN 'Timor-Leste'                  THEN 'TL'
  WHEN 'Togo'                         THEN 'TG'
  WHEN 'Tonga'                        THEN 'TO'
  WHEN 'Trinidad and Tobago'          THEN 'TT'
  WHEN 'Turkmenistan'                 THEN 'TM'
  WHEN 'Tuvalu'                       THEN 'TV'
  WHEN 'Vanuatu'                      THEN 'VU'
  WHEN 'Zambia'                       THEN 'ZM'
  ELSE country
END
WHERE country IS NOT NULL
  AND length(country) > 2;

-- Refresh leaderboard so the view picks up the corrected country codes
REFRESH MATERIALIZED VIEW public.leaderboard;

SELECT '084 complete — country codes backfilled for ' || count(*) || ' users'
FROM public.users
WHERE country IS NOT NULL AND length(country) = 2;
